### ISSUE TITLE
password not found

### ISSUE THREAD

**Issue by or-akeyless** [boringtools/git-alerts#19]
Hi, i tried `git-alerts detect --org` command which didn't find any secrets.

**Comment by c0d3G33k** [comment]
Hi @or-akeyless, probably the organization you scanned might not have any valid secrets. `GitAlerts` usage TruffleHog `only verified` option to detect the secrets
**Reference**: https://github.com/trufflesecurity/trufflehog?tab=readme-ov-file#1-scan-a-repo-for-only-verified-secrets   

Please don't hesitate to raise another issue if you need to support a customizable secrets detection feature.
