### ISSUE TITLE
Allow scan public repos without PAT

### ISSUE THREAD

**Issue by benner** [boringtools/git-alerts#20]
Hello,

Awesome tool!

It would be great if scanning/monitoring for public repos will not require GITHUB_PAT.

**Comment by c0d3G33k** [comment]
Hi @benner , 

Thanks, GitHub only allows `60` requests per hour for unauthenticated API requests, The tool will be more unstable while scanning the larger organizations without the PAT. Let me know your thoughts

**Comment by benner** [comment]
For my case it's enough. Maybe this can be extra flag for this...

**Comment by c0d3G33k** [comment]
@benner, this feature will be released in the attached PR.
