### ISSUE TITLE
Webhooks!

### ISSUE THREAD

**Issue by mattmattmattmattmattmattmattmattmatt** [boringtools/git-alerts#23]
Would be great if you had a webhook integration so that I could integrate your tool beyond Slack :)

**Comment by c0d3G33k** [comment]
@mattmattmattmattmattmattmattmattmatt, thank you for your suggestion. I will look into it and get back to you

**Comment by c0d3G33k** [comment]
@mattmattmattmattmattmattmattmattmatt, it would not be feasible for `GitAlerts` to support webhooks. Which platform do you use? I will add a separate integration for it.
